eshop/urls.py
from django.urls import path
from django.conf.urls import url

from . import views

app_name = 'eshop'

urlpatterns = [
    path('index', views.index, name='index'),
    path('contact', views.contact_us, name='contact'),
    path('categories/<int:division_id>', views.categories, name='categories'),
    path('products/<int:category_id>', views.products, name='products'),
    path('product/<int:product_id>', views.product_view, name='product'),
    path('basket', views.basket, name='basket'),
    path('order', views.order, name='order'),
    url(r'^', views.nothing),
]

# Inside template:
# {{ request.META.HTTP_HOST }}

eshop_server/urls.py
from django.contrib import admin
from django.urls import path, include

from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('eshop.urls', namespace='eshop')),
]  + static(settings.STATIC_URL, document_root=settings.STATIC_ROOT) + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

'''
if settings.DEBUG is True:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)
'''

eshop/models.py
from django.db import models

from django.utils import timezone
from random import randint

class Division(models.Model):
    name = models.CharField(max_length=30, unique=True)

    def __str__(self):
        return "{}".format(self.name)

class Category(models.Model):
    idDivision = models.ForeignKey(Division, on_delete=models.PROTECT)

    name = models.CharField(max_length=30, unique=True)
    image = models.ImageField(upload_to="categories")
    description = models.TextField()

    def __str__(self):
        return "{} - {}".format(self.idDivision, self.name)

class Product(models.Model):
    idCategory = models.ForeignKey(Category, on_delete=models.PROTECT)

    name = models.CharField(max_length=100, unique=True)
    image = models.ImageField(upload_to="products")

    short_description = models.CharField(max_length=300, default="", unique=False)
    description = models.TextField()
    price = models.PositiveSmallIntegerField(default=10)

    in_storage = models.BooleanField(default=False)

    def __str__(self):
        if self.in_storage:
            return "{} (na sklade)".format(self.name)
        else:
            return "Chýba! - {}".format(self.name)

class Specification(models.Model):
    idProduct = models.ForeignKey(Product, on_delete=models.PROTECT)

    name = models.CharField(max_length=50, unique=False)
    value = models.CharField(max_length=50, unique=False)

    def __str__(self):
        return "{} - {}".format(self.name, self.idProduct)

class Gallery(models.Model):
    idProduct = models.ForeignKey(Product, on_delete=models.PROTECT)

    name = models.CharField(max_length=50, unique=True)
    image = models.ImageField(upload_to="gallery")

    def __str__(self):
        return "Image{} - {}".format(self.id, self.idProduct)

class Review(models.Model):
    idProduct = models.ForeignKey(Product, on_delete=models.PROTECT)

    author = models.CharField(max_length=50, unique=False)
    email = models.EmailField(max_length=250)

    text = models.TextField()
    time = models.DateTimeField(default=timezone.now)

    def __str__(self):
        return "{} - {}".format(self.id, self.idProduct)

class Order(models.Model):
    serial_number = models.CharField(max_length=10, unique=True, default='0000000000')

    products = models.ManyToManyField(Product)
    amount = models.TextField()
    price = models.IntegerField(default=0, unique=False)

    getting = models.CharField(max_length=10, unique=False)

    first_name = models.CharField(max_length=50, unique=False)
    surname = models.CharField(max_length=50, unique=False)
    phone = models.CharField(max_length=20, unique=False)

    street = models.CharField(max_length=100, unique=False)
    house = models.CharField(max_length=10, unique=False)
    town = models.CharField(max_length=50, unique=False)
    pdn = models.CharField(max_length=10, unique=False)

    note = models.TextField()

    def __str__(self):
        return "Order {}".format(self.serial_number)

eshop/views.py
from django.shortcuts import render, redirect
from django.http import HttpResponseRedirect

from django.utils import timezone
from django.core.mail import send_mail

from json import dumps, loads
from string import ascii_uppercase, digits
from random import choice

from .models import *

##### Not views #####
def generate_serial():
    numA = ''
    numB = ''

    for i in range(6):
        numA += choice(ascii_uppercase)

    for i in range(4):
        numB += choice(digits)

    num = numA[:4] + numB[:1] + numA[4:] + numB[1:]

    return num

def validate_serial(number):
    try:
        f = open('serial_numbers.txt', 'r')
    except(FileNotFoundError):
        return True

    valid = True
    for line in f:
        if number in line:
            valid = False
            break

    f.close()

    return valid

def register_serial(number):
    with open('serial_numbers.txt', 'a') as f:
        f.write(number + '\n')

def get_serial():
    num = generate_serial()

    while validate_serial(num) != True:
        num = generate_serial()

    register_serial(num)
    return num
####################

def index(request, message=None):
    template = 'eshop/index.html'

    menu = []
    divisions = Division.objects.all()
    for divis in divisions:
        temp = []
        categories = Category.objects.filter(idDivision=divis)
        temp.append(divis)
        temp.append(categories)
        menu.append(temp)

    try:
        message = request.session['message']
    except(KeyError):
        message = None;

    if message:
        del request.session['message']
        return render(request, template, {'message':message, 'menu':menu})
    else:
        return render(request, template, {'menu':menu})

def nothing(request):
    return redirect('eshop:index')

def contact_us(request):
    template = 'eshop/contact_us.html'

    menu = []
    divisions = Division.objects.all()
    for divis in divisions:
        temp = []
        categories = Category.objects.filter(idDivision=divis)
        temp.append(divis)
        temp.append(categories)
        menu.append(temp)

    if request.method == "POST":
        # name not null (html)
        # mail not null (html)
        # subject not null (html)
        subject = str(request.POST['subject'])
        adress = str(request.POST['adress'])
        house = str(request.POST['house'])
        # text not null (html)
        mail_text = str(request.POST['text'])

        try:
            name = str(request.POST['name'])
        except(SyntaxError, NameError, KeyError):
            message = 'Zadajte vaše meno!'
            return render(request, template, {'menu':menu, 'message':message})

        try:
            from_mail = str(request.POST['from'])
        except(SyntaxError, NameError, KeyError):
            message = 'Zadajte správnu emailovú adresu!'
            return render(request, template, {'menu':menu, 'message':message})

        text = "E-mail from: %s\nAdress: %s\nHouse number: %s\n \nText: %s" % (name, adress, house, mail_text)

        try:
            send_mail(subject, text, from_mail, ['mstevko10@gmail.com', 'matkon1999@gmail.com'], fail_silently=False)
        except(ConnectionRefusedError, ConnectionAbortedError, WindowsError, NotImplementedError):
            serial_number = get_serial()
            amount = str(0)

            first_name = "Email"
            surname = "Failure"
            phone_number = "none"

            manner = "User web interface"

            street = "none"
            house_number = "none"
            city_town = "none"
            pdn = "none"

            note = "Error occasioned because of hosting server unavailability."

            ord = Order.objects.create(
                serial_number = serial_number,
                amount = amount,
                price = 0,
                getting = manner,
                first_name = first_name,
                surname = surname,
                phone = phone_number,
                street = street,
                house = house_number,
                town = city_town,
                pdn = pdn,
                note = note
            )

            ord.save()

        mes = 'Správa bola úspešne odoslaná.'
        request.session['message'] = mes

        return redirect('eshop:contact')
    else:
        try:
            message = request.session['message']
        except(KeyError):
            message = None;

        if message:
            del request.session['message']
            return render(request, template, {'message':message, 'menu':menu})
        else:
            return render(request, template, {'menu':menu})

def categories(request, division_id):
    template = 'eshop/categories.html'

    menu = []
    try:
        dvsn = Division.objects.get(pk=division_id)
    except(Division.DoesNotExist):
        mes = 'Hľadaná skupina kategórií neexistuje.'
        request.session['message'] = mes
        return redirect('eshop:index')
    ctgr = Category.objects.filter(idDivision=dvsn)
    divisions = Division.objects.all()

    for divis in divisions:
        if divis != dvsn:
            temp = []
            categories = Category.objects.filter(idDivision=divis)
            temp.append(divis)
            temp.append(categories)
            menu.append(temp)

    try:
        ctgr[0]
    except(IndexError):
        mes = 'Vo vybranej skupine momentálne neexistujú žiadne kategórie produktov.'
        request.session['message'] = mes
        return redirect('eshop:index')

    return render(request, template, {'ctgr':ctgr, 'dvsn':dvsn, 'menu':menu})

def products(request, category_id):
    template = 'eshop/products.html'

    menu = []
    try:
        category = Category.objects.get(pk=category_id)
    except(KeyError, ValueError, NameError, SyntaxError, Category.DoesNotExist):
        mes = 'Hľadaná kategória neexistuje.'
        request.session['message'] = mes
        return redirect('eshop:index')

    dvsn = category.idDivision
    ctgr = Category.objects.filter(idDivision=dvsn)
    divisions = Division.objects.all()

    for divis in divisions:
        if divis != dvsn:
            temp = []
            categories = Category.objects.filter(idDivision=divis)
            temp.append(divis)
            temp.append(categories)
            menu.append(temp)

    products = Product.objects.filter(idCategory=category)

    try:
        products[0]
    except(IndexError):
        mes = 'Vo vybranej kategórii neexistujú žiadne produkty.'
        request.session['message'] = mes
        return redirect('eshop:index')

    return render(request, template, {'ctgr':ctgr, 'dvsn':dvsn, 'category':category, 'products':products, 'menu':menu})

def product_view(request, product_id):
    template = 'eshop/product_view.html'

    try:
        the_product = Product.objects.get(pk=product_id)
    except(KeyError, ValueError, NameError, SyntaxError, Product.DoesNotExist):
        mes = 'Hľadaný produkt neexistuje.'
        request.session['message'] = mes
        return redirect('eshop:index')

    the_specification = Specification.objects.filter(idProduct=the_product)
    the_gallery = Gallery.objects.filter(idProduct=the_product)
    the_review = Review.objects.filter(idProduct=the_product).order_by('-time')

    menu = []
    dvsn = the_product.idCategory.idDivision
    ctgr = Category.objects.filter(idDivision=dvsn)
    divisions = Division.objects.all()

    for divis in divisions:
        if divis != dvsn:
            temp = []
            categories = Category.objects.filter(idDivision=divis)
            temp.append(divis)
            temp.append(categories)
            menu.append(temp)

    if request.method == "POST":
        if "add_to_cart" in request.POST:
            amount = request.POST["amount"]
            temp_cart = [product_id, amount]

            try:
                cart = request.session['cart']
            except(KeyError):
                cart = []

            add = True
            for item in cart:
                if item[0] == temp_cart[0]:
                    item[1] = int(item[1])
                    item[1] += int(temp_cart[1])
                    add = False

            if add:
                cart.append(temp_cart)

            request.session['cart'] = cart

            return redirect('eshop:basket')
        elif "add_review" in request.POST:
            author = str(request.POST["author"])
            mail = request.POST["mail"]
            text = request.POST["text"]

            Review.objects.create(idProduct=the_product, author=author, email=mail, text=text)

            return redirect('eshop:product', product_id)
        else:
            return redirect('eshop:product', product_id)
    else:
        return render(request, template, {
            'the_product':the_product,
            'the_specification':the_specification,
            'the_gallery':the_gallery,
            'the_review':the_review,
            'dvsn':dvsn,
            'ctgr':ctgr,
            'menu':menu
        })

def basket(request):
    template = 'eshop/basket.html'

    try:
        cart = request.session['cart']
    except(KeyError):
        cart = []

    products = Product.objects.all()

    menu = []
    divisions = Division.objects.all()
    for divis in divisions:
        temp = []
        categories = Category.objects.filter(idDivision=divis)
        temp.append(divis)
        temp.append(categories)
        menu.append(temp)

    price_sum = 0
    for item in cart:
        temp_p = Product.objects.get(pk=item[0]).price
        price_sum += int(temp_p)*int(item[1])

    if request.method == "POST":
        for i in range(len(cart)):
            name = 'remove' + str(cart[i][0])

            if name in request.POST:
                del cart[i]
                request.session['cart'] = cart

                return redirect('eshop:basket')

        if "order" in request.POST:
            for item in request.POST:
                item = str(item)

eshop/templates/eshop/basket.html
{% load staticfiles %}

<!-- Auto refresh results -->
<!--<meta http-equiv="refresh" content="5">-->

<!DOCTYPE html>
<html>
  <head>
    <meta charset="utf-8">
    <meta name="description" content="Internetový obchod s vecami pripojitaľnými na internet">
    <meta name="author" content="Martin Nevický & Martin Števko">
    <meta name="keywords" content="eshop, obchod, internet, sieť, veci">
    <meta name="viewport" content="width=device-width, initial-scale=1">

    <meta property="og:url" content="{{ request.META.HTTP_HOST }}" />
    <meta property="og:type" content="website" />
    <meta property="og:title" content="Internet vecí" />
    <meta property="og:description" content="Internetový obchod s vecami pripojitaľnými na internet. Vytvorte si úplne vlatnú kompletnú sieť!" />
    <meta property="og:image" content="{% static 'img/iot_fb.jpg' %}" />

    <title>Košík</title>
    <link rel="icon" href="{% static 'img/logo_invert.png' %}" type="png">
    <link rel="stylesheet" href="{% static 'css/general.css' %}">
    <link rel="stylesheet" href="{% static 'css/alert.css' %}">
    <link rel="stylesheet" href="{% static 'css/basket.css' %}">
  </head>
  <body>
    <header>
      <div class="topnav" id="topnavbar">
        {% if user.is_superuser %}
          <a href="{% url 'admin:index' %}">Administration</a>
        {% endif %}
        <a href="{% url 'eshop:index' %}">Domov</a>

        {% for division in menu %}
          <div class="dropdown">
            <a class="dropbtn" href="{% url 'eshop:categories' division.0.id %}">
              {{ division.0.name }}
            </a>
            <div class="dropdown-content">
              {% for category in division.1 %}
                <a href="{% url 'eshop:products' category.id %}">{{ category.name }}</a>
              {% endfor %}
            </div>
          </div>
        {% endfor %}
        <div id="end">
        <a href="{% url 'eshop:basket' %}" class="active hruba">Košík</a>
        <a href="{% url 'eshop:contact' %}">Kontakt</a>
        <a href="javascript:void(0);" style="font-size:15px;" class="icon" onclick="myFunction()">&#9776;</a>
      </div>
      </div>
    </header>
    <div id="content">
      {% if cart %}
        <br>
        <div class="container-cart">
          <form method="POST" autocomplete="off">
            <ul class="product-list-basic">
              {% csrf_token %}
              {% for item in cart %}
                <div>
                  {% for prod in products %}
                    {% if prod.id == item.0 %}
                      <li>
                        <h3><a>{{ prod.name }}</a></h3>
                        <a class="product-photo">
                          <img src="{{ prod.image.url }}" alt="{{ prod.name }}" width="15%">
                        </a>

                        <p class="total">Cena za kus: &nbsp <span class="price" style="color:black"><b>{{ prod.price }}&euro;</b></span></p>

                        <input name="amount{{ item.0 }}" type="number" min="1" value="{{ item.1 }}" required>
                        <input name="remove{{ item.0 }}" type="submit" value="Odobrať z košíka" class="rem">
                      </li>
                    {% endif %}
                  {% endfor %}
                </div>
              {% endfor %}
            </ul>
            <hr>
            <p class="total">Celkovo: &nbsp <span class="price" style="color:black"><b>{{ price_sum }}&euro;</b></span></p>

          <input type="submit" value="Prejsť na objednávku" class="btn" name="order">
          </form>
        </div>
      {% else %}
        <div class="container">
          <h1>Košík</h1>
          <div id="alertX71" class="message info" style="margin: 0 0 10px 0;">
            V tejto chvíli sa v košíku nenachádzajú žiadne položky.
            <button type="button" onclick="close_this('alertX71');" class="close_alert info">&#x2716;</button>
          </div>
          <div style="clear: both;"></div>
        </div>
      {% endif %}
    </div>
    <footer class="footer">
      <a class="foot" href="https://github.com/MartinStevko/SEN_eshop">Zdrojový kód - ESHOP ©MARTINNEVICKY&MARTINSTEVKO2018</a>
    </footer>
  </body>
  <script type="text/javascript" src="{% static 'js/navbar.js' %}"></script>
  <script type="text/javascript" src="{% static 'js/alert.js' %}"></script>
</html>

eshop/templates/eshop/categories.html
{% load staticfiles %}

<!-- Auto refresh results -->
<!--<meta http-equiv="refresh" content="5">-->

<!DOCTYPE html>
<html>
  <head>
    <meta charset="utf-8">
    <meta name="description" content="Internetový obchod s vecami pripojitaľnými na internet">
    <meta name="author" content="Martin Nevický & Martin Števko">
    <meta name="keywords" content="eshop, obchod, internet, sieť, veci">
    <meta name="viewport" content="width=device-width, initial-scale=1">

    <meta property="og:url" content="{{ request.META.HTTP_HOST }}" />
    <meta property="og:type" content="website" />
    <meta property="og:title" content="Internet vecí" />
    <meta property="og:description" content="Internetový obchod s vecami pripojitaľnými na internet. Vytvorte si úplne vlatnú kompletnú sieť!" />
    <meta property="og:image" content="{% static 'img/iot_fb.jpg' %}" />

    <title>Kategórie produktov</title>
    <link rel="icon" href="{% static 'img/logo_invert.png' %}" type="png">
    <link rel="stylesheet" href="{% static 'css/general.css' %}">
    <link rel="stylesheet" href="{% static 'css/categories.css' %}">
  </head>
  <body>
    <header>
      <div class="topnav" id="topnavbar">
        {% if user.is_superuser %}
          <a href="{% url 'admin:index' %}">Administration</a>
        {% endif %}
        <a href="{% url 'eshop:index' %}">Domov</a>
        <div class="dropdown active">
          <a class="active dropbtn" href="{% url 'eshop:categories' dvsn.id %}">
            {{ dvsn.name }}
          </a>
          <div class="dropdown-content">
            {% for category in ctgr %}
              <a href="{% url 'eshop:products' category.id %}">{{ category.name }}</a>
            {% endfor %}
          </div>
        </div>

        {% for division in menu %}
          <div class="dropdown">
            <a class="dropbtn" href="{% url 'eshop:categories' division.0.id %}">
              {{ division.0.name }}
            </a>
            <div class="dropdown-content">
              {% for category in division.1 %}
                <a href="{% url 'eshop:products' category.id %}">{{ category.name }}</a>
              {% endfor %}
            </div>
          </div>
        {% endfor %}
        <div id="end">
        <a href="{% url 'eshop:basket' %}">Košík</a>
        <a href="{% url 'eshop:contact' %}">Kontakt</a>
        <a href="javascript:void(0);" style="font-size:15px;" class="icon" onclick="myFunction()">&#9776;</a>
      </div>
      </div>
    </header>
    <div id="content">
      <ul class="cat-list-basic">
        {% for category in ctgr %}
          <li>
            <a href="{% url 'eshop:products' category.id %}">
              <img src="{{ category.image.url }}" alt="{{ category.name }}">
            </a>
            <div>
              <h2><a href="{% url 'eshop:products' category.id %}">{{ category.name }}</a></h2>
              <p>{{ category.description }}</p>
              <a href="{% url 'eshop:products' category.id %}" class="read-more">Zobraziť kategóriu &rarr;</a>
            </div>
          </li>
        {% endfor %}
      </ul>
    </div>
    <footer class="footer">
      <a class="foot" href="https://github.com/MartinStevko/SEN_eshop">Zdrojový kód - ESHOP ©MARTINNEVICKY&MARTINSTEVKO2018</a>
    </footer>
  </body>
  <script type="text/javascript" src="{% static 'js/navbar.js' %}"></script>
</html>

eshop/templates/eshop/contact_us.html
{% load staticfiles %}

<!-- Auto refresh results -->
<!--<meta http-equiv="refresh" content="5">-->

<!DOCTYPE html>
<html>
  <head>
    <meta charset="utf-8">
    <meta name="description" content="Internetový obchod s vecami pripojitaľnými na internet">
    <meta name="author" content="Martin Nevický & Martin Števko">
    <meta name="keywords" content="eshop, obchod, internet, sieť, veci">
    <meta name="viewport" content="width=device-width, initial-scale=1">

    <meta property="og:url" content="{{ request.META.HTTP_HOST }}" />
    <meta property="og:type" content="website" />
    <meta property="og:title" content="Internet vecí" />
    <meta property="og:description" content="Internetový obchod s vecami pripojitaľnými na internet. Vytvorte si úplne vlatnú kompletnú sieť!" />
    <meta property="og:image" content="{% static 'img/iot_fb.jpg' %}" />

    <title>Kontakt</title>
    <link rel="icon" href="{% static 'img/logo_invert.png' %}" type="png">
    <link rel="stylesheet" href="{% static 'css/contact_us.css' %}">
    <link rel="stylesheet" href="{% static 'css/general.css' %}">
  </head>
  <body>
    <header>
      <div class="topnav" id="topnavbar">
        {% if user.is_superuser %}
          <a href="{% url 'admin:index' %}">Administration</a>
        {% endif %}
        <a href="{% url 'eshop:index' %}">Domov</a>

        {% for division in menu %}
          <div class="dropdown">
            <a class="dropbtn" href="{% url 'eshop:categories' division.0.id %}">
              {{ division.0.name }}
            </a>
            <div class="dropdown-content">
              {% for category in division.1 %}
                <a href="{% url 'eshop:products' category.id %}">{{ category.name }}</a>
              {% endfor %}
            </div>
          </div>
        {% endfor %}
        <div id="end">
        <a href="{% url 'eshop:basket' %}">Košík</a>
        <a href="{% url 'eshop:contact' %}" class="active hruba">Kontakt</a>
        <a href="javascript:void(0);" style="font-size:15px;" class="icon" onclick="myFunction()">&#9776;</a>
      </div>
      </div>
    </header>
    <div id="content" class="container">
      <div id="form">
        <h1>Napíšte nám správu</h1>
        {% if message %}
          <div id="alertX72" class="message success">
            {{ message }}
            <button type="button" onclick="close_this('alertX72');" class="close_alert success">&#x2716;</button>
          </div>
          <div style="clear: both;"></div>
        {% endif %}
        <form method="POST" autocomplete="off">
          {% csrf_token %}

          <div class="row">
            <div class="con-1">
              <label for="1">Meno a priezvisko*:</label>
            </div>
            <div class="con-2">
              <input id="1" name="name" type="text" maxlength="50" required>
            </div>
          </div>

          <div class="row">
            <div class="con-1">
              <label for="2">E-mail*:</label>
            </div>
            <div class="con-2">
              <input id="2" name="from" type="email" required>
            </div>
          </div>

          <div class="row">
            <div class="con-1">
              <label for="3">Predmet*:</label>
            </div>
            <div class="con-2">
              <input id="3" name="subject" type="text" maxlength="50" required>
            </div>
          </div>

          <div class="row">
            <div class="con-1">
              <label for="4">Adresa bydliska:</label>
            </div>
            <div class="con-2">
              <input id="4" name="adress" type="text" maxlength="150">
            </div>
          </div>

          <div class="row">
            <div class="con-1">
              <label for="5">Číslo domu:</label>
            </div>
            <div class="con-3">
              <input id="5" name="house" type="text" maxlength="10">
            </div>
          </div>

          <div class="row">
            <div class="con-1">
              <label for="6">Správa*:</label>
            </div>
            <div class="con-2">
              <textarea id="6" name="text" rows="6" cols="50" style="height:200px" required></textarea>
            </div>
          </div>

          <br>

          <div class="row">
            <input type="submit" value="Odoslať" name="submit">
          </div>
        </form>
      </div>
    </div>
    <footer class="footer">
      <a class="foot" href="https://github.com/MartinStevko/SEN_eshop">Zdrojový kód - ESHOP ©MARTINNEVICKY&MARTINSTEVKO2018</a>
    </footer>
  </body>
  <script type="text/javascript" src="{% static 'js/navbar.js' %}"></script>
  <script type="text/javascript" src="{% static 'js/alert.js' %}"></script>
</html>

eshop/templates/eshop/products.html
{% load staticfiles %}

<!-- Auto refresh results -->
<!--<meta http-equiv="refresh" content="5">-->

<!DOCTYPE html>
<html>
  <head>
    <meta charset="utf-8">
    <meta name="description" content="Internetový obchod s vecami pripojitaľnými na internet">
    <meta name="author" content="Martin Nevický & Martin Števko">
    <meta name="keywords" content="eshop, obchod, internet, sieť, veci">
    <meta name="viewport" content="width=device-width, initial-scale=1">

    <meta property="og:url" content="{{ request.META.HTTP_HOST }}" />
    <meta property="og:type" content="website" />
    <meta property="og:title" content="Internet vecí" />
    <meta property="og:description" content="Internetový obchod s vecami pripojitaľnými na internet. Vytvorte si úplne vlatnú kompletnú sieť!" />
    <meta property="og:image" content="{% static 'img/iot_fb.jpg' %}" />

    <title>Produkty</title>
    <link rel="icon" href="{% static 'img/logo_invert.png' %}" type="png">
    <link rel="stylesheet" href="{% static 'css/general.css' %}">
    <link rel="stylesheet" href="{% static 'css/products.css' %}">
  </head>
  <body>
    <header>
      <div class="topnav" id="topnavbar">
        {% if user.is_superuser %}
          <a href="{% url 'admin:index' %}">Administration</a>
        {% endif %}
        <a href="{% url 'eshop:index' %}">Domov</a>
        <div class="dropdown active">
          <a class="active dropbtn" href="{% url 'eshop:categories' dvsn.id %}">
            {{ dvsn.name }}
          </a>
          <div class="dropdown-content">
            {% for cat in ctgr %}
              <a href="{% url 'eshop:products' cat.id %}">{{ cat.name }}</a>
            {% endfor %}
          </div>
        </div>

        {% for division in menu %}
          <div class="dropdown">
            <a class="dropbtn" href="{% url 'eshop:categories' division.0.id %}">
              {{ division.0.name }}
            </a>
            <div class="dropdown-content">
              {% for cat in division.1 %}
                <a href="{% url 'eshop:products' cat.id %}">{{ cat.name }}</a>
              {% endfor %}
            </div>
          </div>
        {% endfor %}
        <div id="end">
        <a href="{% url 'eshop:basket' %}">Košík</a>
        <a href="{% url 'eshop:contact' %}">Kontakt</a>
        <a href="javascript:void(0);" style="font-size:15px;" class="icon" onclick="myFunction()">&#9776;</a>
      </div>
      </div>
    </header>
    <div id="content">

      <br>

      <ul class="product-list-basic">
        {% for product in products %}
          <li>
            <a href="{% url 'eshop:product' product.id %}" class="product-photo">
                <img src="{{ product.image.url }}" alt="{{ product.name }}" height="130px">
            </a>

            <h2><a href="{% url 'eshop:product' product.id %}">{{ product.name }}</a></h2>

            <p class="product-description">{{ product.short_description }}</p>

            <a class="button_A" href="{% url 'eshop:product' product.id %}">Pozrieť produkt</a>
            <p class="product-price">{{ product.price }}&euro;</p>
          </li>
        {% endfor %}
      </ul>
    </div>
    <footer class="footer">
      <a class="foot" href="https://github.com/MartinStevko/SEN_eshop">Zdrojový kód - ESHOP ©MARTINNEVICKY&MARTINSTEVKO2018</a>
    </footer>
  </body>
  <script type="text/javascript" src="{% static 'js/navbar.js' %}"></script>
</html>